# Generated by Django 3.2.9 on 2022-03-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('SurveyId', models.CharField(blank=True, max_length=500)),
                ('Latitude', models.CharField(blank=True, max_length=500)),
                ('Longitude', models.CharField(blank=True, max_length=500)),
                ('Username', models.CharField(blank=True, max_length=500)),
                ('Date_Time', models.DateTimeField(blank=True, null=True)),
                ('SubDivision', models.CharField(blank=True, max_length=500)),
                ('Section', models.CharField(blank=True, max_length=500)),
                ('BuildingReferenceNumber', models.CharField(blank=True, max_length=500)),
                ('ConnectedPoleNo', models.CharField(blank=True, max_length=500)),
                ('PaintedPoleNo', models.CharField(blank=True, max_length=500)),
                ('FeederName', models.CharField(blank=True, max_length=500)),
                ('DTCode', models.CharField(blank=True, max_length=500)),
                ('ConsumerName', models.CharField(blank=True, max_length=500)),
                ('NewAccountNumber', models.CharField(blank=True, max_length=500)),
                ('OldAccountNumber', models.CharField(blank=True, max_length=500)),
                ('SCNumber', models.CharField(blank=True, max_length=500)),
                ('CustomerMobileNumber', models.CharField(blank=True, max_length=500)),
                ('FlatNo', models.CharField(blank=True, max_length=500)),
                ('Address1', models.CharField(blank=True, max_length=500)),
                ('Address2', models.CharField(blank=True, max_length=500)),
                ('Address3', models.CharField(blank=True, max_length=500)),
                ('ConsumerDoorLock', models.CharField(blank=True, max_length=500)),
                ('AMRInstalled', models.CharField(blank=True, max_length=500)),
                ('CommunicationType', models.CharField(blank=True, max_length=500)),
                ('CTRatio', models.CharField(blank=True, max_length=500)),
                ('DisplayCondition', models.CharField(blank=True, max_length=500)),
                ('MaximumDemand', models.CharField(blank=True, max_length=500)),
                ('MeterAvailability', models.CharField(blank=True, max_length=500)),
                ('MeterBox', models.CharField(blank=True, max_length=500)),
                ('MeterLocation', models.CharField(blank=True, max_length=500)),
                ('HeightGT5ft', models.CharField(blank=True, max_length=500)),
                ('MeterStatus', models.CharField(blank=True, max_length=500)),
                ('NominalVoltage', models.CharField(blank=True, max_length=500)),
                ('PhaseConnection', models.CharField(blank=True, max_length=500)),
                ('SealCondition', models.CharField(blank=True, max_length=500)),
                ('SealType', models.CharField(blank=True, max_length=500)),
                ('TotalMF', models.CharField(blank=True, max_length=500)),
                ('kWh', models.CharField(blank=True, max_length=500)),
                ('Bypass', models.CharField(blank=True, max_length=500)),
                ('Category', models.CharField(blank=True, max_length=500)),
                ('Type', models.CharField(blank=True, max_length=500)),
                ('SubType', models.CharField(blank=True, max_length=500)),
                ('MeterSerialNumber', models.CharField(blank=True, max_length=500)),
                ('MeterMake', models.CharField(blank=True, max_length=500)),
                ('Theft', models.CharField(blank=True, max_length=500)),
                ('BillDelivered', models.CharField(blank=True, max_length=500)),
                ('BillShown', models.CharField(blank=True, max_length=500)),
                ('MeterPhoto', models.ImageField(blank=True, upload_to='static/media/TPWODL/MeterPhoto/')),
                ('BillPhoto', models.ImageField(blank=True, upload_to='static/media/TPWODL/BillPhoto/')),
                ('OtherPhoto', models.ImageField(blank=True, upload_to='static/media/TPWODL/OtherPhoto/')),
                ('NeighbouringMeterNo', models.CharField(blank=True, max_length=500)),
                ('NeighbouringConsumerNo', models.CharField(blank=True, max_length=500)),
                ('NoofDigits', models.CharField(blank=True, max_length=500)),
                ('SurveyorRemark', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'Consumer',
            },
        ),
    ]
